[project]
name = "{{cookiecutter.project_slug}}"
version = "0.0.1"
description = "A new process-bigraph project"
readme = "README.md"
requires-python = "==3.12.9"
dependencies = [
    "process-bigraph",
]

[tool.setuptools]
packages = [
    "{{cookiecutter.project_slug}}"
]

